import { readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { EDGES, FLOWS, LANES, NODES, type FlowEdge } from "../src/demo/flow-graph.js";
import { SCENARIOS } from "../src/demo/scenarios/index.js";

const root = fileURLToPath(new URL("../", import.meta.url));

// Quoted Mermaid labels still interpret HTML/entities. Encode punctuation that
// can terminate a label or introduce markup; node IDs never contain model text.
const label = (text: string): string => text.replace(/&/g, "#38;").replace(/"/g, "#quot;").replace(/</g, "#60;").replace(/>/g, "#62;");
const nodeId = (id: string): string => `n${NODES.findIndex((node) => node.id === id)}`;

function diagram(edges: readonly FlowEdge[], overview = false): string {
  const used = new Set(edges.flatMap((edge) => [edge.from, edge.to]));
  const lines = ["```mermaid", "flowchart LR"];
  for (const lane of LANES) {
    const nodes = NODES.filter((node) => node.lane === lane.id && (overview || used.has(node.id)));
    if (!nodes.length) continue;
    if (overview) lines.push(`  subgraph lane_${lane.id}["${label(lane.label)}"]`);
    for (const node of nodes) {
      const text = `"${label(node.label)}"`;
      const shape = node.kind === "decision" ? `{${text}}` : node.kind === "terminal" ? `([${text}])` : `[${text}]`;
      lines.push(`    ${nodeId(node.id)}${shape}`);
    }
    if (overview) lines.push("  end");
  }
  for (const edge of edges) lines.push(`  ${nodeId(edge.from)} -->|"${label(edge.label)}"| ${nodeId(edge.to)}`);
  return [...lines, "```"].join("\n");
}

/** Deterministic renderer shared by the CLI and the checked-in-doc drift guard. */
export function renderFlows(): string {
  const adrFiles = readdirSync(resolve(root, "docs/adr")).sort();
  const adrLink = (adr: string): string => {
    const file = adrFiles.find((name) => name.startsWith(`${adr.replace("ADR-", "")}-`));
    if (!file) throw new Error(`Missing document for ${adr}`);
    return `[${adr}](adr/${file})`;
  };
  const lines = [
    "# Workflow flows",
    "",
    "<!-- Generated by scripts/gen-flows.ts. Edit the model and scenarios, then run npm run docs:flows. -->",
    "",
    "Generated from [the flow model](../src/demo/flow-graph.ts) and [the scenario registry](../src/demo/scenarios/index.ts). The dashboard's `/flow` endpoint serves the same graph. Run `node dist/cli.js serve --demo` to explore scenario frames through `/demo/scenarios` and `/actions/demo`; see [the demo guide](../demo.md).",
    "",
    "`npm test` requires scenarios to visit every model edge and demonstrate every flow, and checks this file for drift. Coverage describes the modeled transitions; scenarios fake I/O and record real pure decider calls.",
    "",
    "## Overview",
    "",
    diagram(EDGES, true),
  ];
  for (const flow of FLOWS) {
    const edges = EDGES.filter((edge) => edge.flows.includes(flow.id));
    const used = new Set(edges.flatMap((edge) => [edge.from, edge.to]));
    const nodes = NODES.filter((node) => used.has(node.id));
    lines.push("", `## ${flow.title}`, "", flow.summary, "",
      `Design: ${flow.adr ? adrLink(flow.adr) : "No dedicated ADR in the model."}`, "", diagram(edges), "", "Code references:", "");
    for (const ref of new Set(nodes.map((node) => node.codeRef))) {
      const [file, symbol] = ref.split("#");
      lines.push(`- [${file}](../${file})${symbol ? ` — \`${symbol}\`` : ""}`);
    }
    lines.push("", "Scenarios:", "");
    for (const scenario of SCENARIOS.filter((scenario) => scenario.flows.includes(flow.id))) {
      lines.push(`- **${scenario.title}** (\`${scenario.id}\`): ${scenario.summary}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeFileSync(resolve(root, "docs/FLOWS.md"), renderFlows(), "utf8");
}
